name: Windup
title: Windup Migration Platform
org: Red Hat
base_url: '/staging'
dcp_base_protocol_relative_url: //dcp.jboss.org/

deploy_base: &deploy
  host: design@filemgmt.jboss.org
  
profiles:

  development: &development
    base_url: /

  staging: 
    base_url: http://windup.jboss.org/staging/
    deploy:
      <<: *deploy
      path: /www_htdocs/windup/staging
    
  production: 
    base_url: http://windup.jboss.org/production/
    deploy:
      <<: *deploy
      path: /www_htdocs/windup/production
